import { z } from "zod";
import {
  AnalyticsQuery,
  AppSettingKey,
  UpdateProfileInput,
  ListSandboxesQuery,
  ServiceSecretKey,
  SetAppSettingInput,
  SetServiceSecretInput,
} from "@open-agents/types";
import { defineControlPlaneTool, idParam } from "../defineTool.js";

const sandboxIdParam = {
  id: z.string().min(1).describe("Sandbox id"),
} as const;

const conversationIdParam = {
  conversationId: z.string().min(1).describe("Chat conversation id"),
} as const;

const threadIdParam = {
  threadId: z.string().min(1).describe("Email thread id"),
} as const;

export const adminControlPlaneTools = [
  defineControlPlaneTool({
    name: "profile_get",
    title: "Get profile",
    description: "Get the signed-in user profile.",
    auth: "user",
    method: "GET",
    path: "/api/profile",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "profile_update",
    title: "Update profile",
    description:
      "Update the signed-in user's display name and optional profile fields that profile-aware agents may receive when enabled.",
    auth: "user",
    method: "PATCH",
    path: "/api/profile",
    input: UpdateProfileInput,
  }),
  defineControlPlaneTool({
    name: "mcp_connection_info",
    title: "MCP connection info",
    description: "Get MCP server URL and OAuth metadata for this deployment.",
    auth: "user",
    method: "GET",
    path: "/api/mcp-connection/info",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "mcp_connection_tokens_list",
    title: "List MCP bearer tokens",
    description: "List active manual MCP bearer tokens for the signed-in user.",
    auth: "user",
    method: "GET",
    path: "/api/mcp-connection/tokens",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "mcp_connection_tokens_create",
    title: "Create MCP bearer token",
    description: "Generate a long-lived bearer token for MCP clients.",
    auth: "user",
    method: "POST",
    path: "/api/mcp-connection/tokens",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "mcp_connection_tokens_revoke",
    title: "Revoke MCP bearer token",
    description: "Revoke a manual MCP bearer token.",
    auth: "user",
    method: "DELETE",
    path: "/api/mcp-connection/tokens/:id",
    pathParams: ["id"],
    input: z.object(idParam),
  }),
  defineControlPlaneTool({
    name: "settings_public",
    title: "Get public settings",
    description: "Get public branding settings (no auth).",
    auth: "public",
    method: "GET",
    path: "/api/settings/public",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "settings_list",
    title: "List settings",
    description: "List deployment app settings (plaintext values).",
    auth: "user",
    method: "GET",
    path: "/api/settings",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "settings_upsert",
    title: "Set app setting",
    description: "Set or clear a deployment app setting by key.",
    auth: "admin",
    method: "PUT",
    path: "/api/settings/:key",
    pathParams: ["key"],
    input: SetAppSettingInput.extend({
      key: AppSettingKey.describe("App setting key"),
    }),
  }),
  defineControlPlaneTool({
    name: "settings_delete",
    title: "Delete app setting",
    description: "Delete a deployment app setting.",
    auth: "admin",
    method: "DELETE",
    path: "/api/settings/:key",
    pathParams: ["key"],
    input: z.object({
      key: AppSettingKey.describe("App setting key"),
    }),
  }),
  defineControlPlaneTool({
    name: "secrets_list",
    title: "List secrets",
    description: "List which service secret keys are configured (not values).",
    auth: "admin",
    method: "GET",
    path: "/api/secrets",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "secrets_upsert",
    title: "Set service secret",
    description: "Set an encrypted service credential (API keys, Mailgun, etc.).",
    auth: "admin",
    method: "PUT",
    path: "/api/secrets/:key",
    pathParams: ["key"],
    input: SetServiceSecretInput.extend({
      key: ServiceSecretKey.describe("Service secret key"),
    }),
  }),
  defineControlPlaneTool({
    name: "secrets_delete",
    title: "Delete service secret",
    description: "Delete a service credential.",
    auth: "admin",
    method: "DELETE",
    path: "/api/secrets/:key",
    pathParams: ["key"],
    input: z.object({
      key: ServiceSecretKey.describe("Service secret key"),
    }),
  }),
  defineControlPlaneTool({
    name: "sandboxes_list",
    title: "List sandboxes",
    description: "List Daytona sandboxes with optional filters.",
    auth: "admin",
    method: "GET",
    path: "/api/sandboxes",
    queryFields: ["agentId", "state", "surface", "limit", "offset"],
    input: ListSandboxesQuery,
  }),
  defineControlPlaneTool({
    name: "sandboxes_orphans",
    title: "List orphan sandboxes",
    description: "List Daytona sandboxes not registered in the database.",
    auth: "admin",
    method: "GET",
    path: "/api/sandboxes/orphans",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "sandboxes_reconcile",
    title: "Reconcile sandboxes",
    description: "Run sandbox lifecycle reconciliation.",
    auth: "admin",
    method: "POST",
    path: "/api/sandboxes/reconcile",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "sandboxes_by_conversation",
    title: "Get sandbox by conversation",
    description: "Look up sandbox metadata for a chat conversation.",
    auth: "admin",
    method: "GET",
    path: "/api/sandboxes/by-conversation/:conversationId",
    pathParams: ["conversationId"],
    input: z.object(conversationIdParam),
  }),
  defineControlPlaneTool({
    name: "sandboxes_by_thread",
    title: "Get sandbox by email thread",
    description: "Look up sandbox metadata for an email thread.",
    auth: "admin",
    method: "GET",
    path: "/api/sandboxes/by-thread/:threadId",
    pathParams: ["threadId"],
    input: z.object(threadIdParam),
  }),
  defineControlPlaneTool({
    name: "sandboxes_get",
    title: "Get sandbox",
    description: "Get sandbox metadata by id.",
    auth: "admin",
    method: "GET",
    path: "/api/sandboxes/:id",
    pathParams: ["id"],
    input: z.object(sandboxIdParam),
  }),
  defineControlPlaneTool({
    name: "sandboxes_sync",
    title: "Sync sandbox",
    description: "Sync sandbox state from the Daytona provider.",
    auth: "admin",
    method: "POST",
    path: "/api/sandboxes/:id/sync",
    pathParams: ["id"],
    input: z.object(sandboxIdParam),
  }),
  defineControlPlaneTool({
    name: "sandboxes_stop",
    title: "Stop sandbox",
    description: "Stop a running sandbox.",
    auth: "admin",
    method: "POST",
    path: "/api/sandboxes/:id/stop",
    pathParams: ["id"],
    input: z.object(sandboxIdParam),
  }),
  defineControlPlaneTool({
    name: "sandboxes_start",
    title: "Start sandbox",
    description: "Start a stopped sandbox.",
    auth: "admin",
    method: "POST",
    path: "/api/sandboxes/:id/start",
    pathParams: ["id"],
    input: z.object(sandboxIdParam),
  }),
  defineControlPlaneTool({
    name: "sandboxes_archive",
    title: "Archive sandbox",
    description: "Archive a sandbox.",
    auth: "admin",
    method: "POST",
    path: "/api/sandboxes/:id/archive",
    pathParams: ["id"],
    input: z.object(sandboxIdParam),
  }),
  defineControlPlaneTool({
    name: "sandboxes_recover",
    title: "Recover sandbox",
    description: "Recover an archived sandbox.",
    auth: "admin",
    method: "POST",
    path: "/api/sandboxes/:id/recover",
    pathParams: ["id"],
    input: z.object(sandboxIdParam),
  }),
  defineControlPlaneTool({
    name: "sandboxes_delete",
    title: "Delete sandbox",
    description: "Delete sandbox metadata and clear conversation/thread pointers.",
    auth: "admin",
    method: "DELETE",
    path: "/api/sandboxes/:id",
    pathParams: ["id"],
    input: z.object(sandboxIdParam),
  }),
  defineControlPlaneTool({
    name: "analytics_get",
    title: "Get analytics",
    description: "Get usage analytics for operators.",
    auth: "operator",
    method: "GET",
    path: "/api/analytics",
    queryFields: ["window", "from", "to"],
    input: AnalyticsQuery,
  }),
  defineControlPlaneTool({
    name: "health_check",
    title: "Health check",
    description: "Liveness health check.",
    auth: "public",
    method: "GET",
    path: "/health",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "health_ready",
    title: "Readiness check",
    description: "Readiness check (includes database connectivity).",
    auth: "public",
    method: "GET",
    path: "/health/ready",
    input: z.object({}),
  }),
];
