import { z } from "zod";
import {
  CreateMcpServerInput,
  ProbeMcpServerInput,
  ProbeStoredMcpServerInput,
  UpdateMcpServerInput,
} from "@open-agents/types";
import { defineControlPlaneTool, idParam } from "../defineTool.js";

export const libraryControlPlaneTools = [
  defineControlPlaneTool({
    name: "tools_list",
    title: "List tool catalog",
    description: "List managed and platform tools in the unified catalog.",
    auth: "user",
    method: "GET",
    path: "/api/tools",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "models_catalog",
    title: "List models",
    description: "List model providers and model ids available for agents.",
    auth: "user",
    method: "GET",
    path: "/api/models/catalog",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "skills_list",
    title: "List skills",
    description: "List skill bundles in the library.",
    auth: "user",
    method: "GET",
    path: "/api/skills",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "skills_delete",
    title: "Delete skill",
    description: "Delete a skill bundle and all versions.",
    auth: "admin",
    method: "DELETE",
    path: "/api/skills/:id",
    pathParams: ["id"],
    input: z.object(idParam),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_probe_draft",
    title: "Probe MCP server URL",
    description: "Test connectivity to an unsaved MCP server URL.",
    auth: "admin",
    method: "POST",
    path: "/api/mcp-servers/probe",
    input: ProbeMcpServerInput,
  }),
  defineControlPlaneTool({
    name: "mcp_servers_list",
    title: "List MCP servers",
    description: "List third-party MCP servers in the deployment library.",
    auth: "user",
    method: "GET",
    path: "/api/mcp-servers",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_get",
    title: "Get MCP server",
    description: "Get MCP server library entry by id.",
    auth: "user",
    method: "GET",
    path: "/api/mcp-servers/:id",
    pathParams: ["id"],
    input: z.object(idParam),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_create",
    title: "Create MCP server",
    description: "Register a third-party MCP server in the library.",
    auth: "admin",
    method: "POST",
    path: "/api/mcp-servers",
    input: CreateMcpServerInput,
  }),
  defineControlPlaneTool({
    name: "mcp_servers_update",
    title: "Update MCP server",
    description: "Update MCP server library entry.",
    auth: "admin",
    method: "PATCH",
    path: "/api/mcp-servers/:id",
    pathParams: ["id"],
    input: UpdateMcpServerInput.extend(idParam),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_delete",
    title: "Delete MCP server",
    description: "Remove an MCP server from the library.",
    auth: "admin",
    method: "DELETE",
    path: "/api/mcp-servers/:id",
    pathParams: ["id"],
    input: z.object(idParam),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_probe",
    title: "Probe stored MCP server",
    description: "Test connectivity to a stored MCP server (optional bearer override).",
    auth: "admin",
    method: "POST",
    path: "/api/mcp-servers/:id/probe",
    pathParams: ["id"],
    input: ProbeStoredMcpServerInput.extend(idParam),
  }),
];
