import { z } from "zod";
import {
  CreateMcpServerInput,
  CreateSkillUploadRequestInput,
  ProbeMcpServerInput,
  ProbeStoredMcpServerInput,
  UpdateMcpServerInput,
} from "@open-agents/types";
import { defineControlPlaneTool, idParam } from "../defineTool.js";

export const libraryControlPlaneTools = [
  defineControlPlaneTool({
    name: "tools_list",
    title: "List tool catalog",
    description: "List managed and platform tools in the unified catalog.",
    auth: "user",
    method: "GET",
    path: "/api/tools",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "models_catalog",
    title: "List models",
    description: "List model providers and model ids available for agents.",
    auth: "user",
    method: "GET",
    path: "/api/models/catalog",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "skills_list",
    title: "List skills",
    description: "List skill bundles in the library.",
    auth: "user",
    method: "GET",
    path: "/api/skills",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "skill_download_link",
    title: "Get control-plane skill download link",
    description:
      "Return a public download URL and install instructions for the latest Open Agents control-plane agent skill bundle (.skill), compiled from this deployment's docs. Fetch the URL and unzip it into your skills directory to install it as a normal skill — do not inline its contents into context. No authentication is required to download.",
    auth: "public",
    method: "GET",
    path: "/api/skills/control-plane",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "skills_create",
    title: "Upload a skill bundle (get signed URL)",
    description:
      "Request a short-lived, single-use signed URL for uploading a skill bundle — a .zip whose top level contains a SKILL.md. Provide the skill `name`; if a skill with that name already exists the upload becomes a new version of it, otherwise a new skill is created.",
    notes:
      "Returns { action, uploadUrl, method: 'PUT', contentType: 'application/zip', expiresAt }. This tool does NOT transfer the bundle: after calling it, PUT the raw zip bytes to uploadUrl, e.g. `curl -X PUT --data-binary @bundle.zip \"<uploadUrl>\"`. The URL is single-use and expires (~15 min) — request a new one if it lapses or the upload fails. Requires an environment with a filesystem to hold the bundle.",
    auth: "admin",
    method: "POST",
    path: "/api/skills/upload-requests",
    input: CreateSkillUploadRequestInput,
  }),
  defineControlPlaneTool({
    name: "skills_delete",
    title: "Delete skill",
    description: "Delete a skill bundle and all versions.",
    auth: "admin",
    method: "DELETE",
    path: "/api/skills/:id",
    pathParams: ["id"],
    input: z.object(idParam),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_probe_draft",
    title: "Probe MCP server URL",
    description: "Test connectivity to an unsaved MCP server URL.",
    auth: "admin",
    method: "POST",
    path: "/api/mcp-servers/probe",
    input: ProbeMcpServerInput,
  }),
  defineControlPlaneTool({
    name: "mcp_servers_list",
    title: "List MCP servers",
    description: "List third-party MCP servers in the deployment library.",
    auth: "user",
    method: "GET",
    path: "/api/mcp-servers",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_get",
    title: "Get MCP server",
    description: "Get MCP server library entry by id.",
    auth: "user",
    method: "GET",
    path: "/api/mcp-servers/:id",
    pathParams: ["id"],
    input: z.object(idParam),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_create",
    title: "Create MCP server",
    description: "Register a third-party MCP server in the library.",
    auth: "admin",
    method: "POST",
    path: "/api/mcp-servers",
    input: CreateMcpServerInput,
  }),
  defineControlPlaneTool({
    name: "mcp_servers_update",
    title: "Update MCP server",
    description: "Update MCP server library entry.",
    auth: "admin",
    method: "PATCH",
    path: "/api/mcp-servers/:id",
    pathParams: ["id"],
    input: UpdateMcpServerInput.extend(idParam),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_delete",
    title: "Delete MCP server",
    description: "Remove an MCP server from the library.",
    auth: "admin",
    method: "DELETE",
    path: "/api/mcp-servers/:id",
    pathParams: ["id"],
    input: z.object(idParam),
  }),
  defineControlPlaneTool({
    name: "mcp_servers_probe",
    title: "Probe stored MCP server",
    description: "Test connectivity to a stored MCP server (optional bearer override).",
    auth: "admin",
    method: "POST",
    path: "/api/mcp-servers/:id/probe",
    pathParams: ["id"],
    input: ProbeStoredMcpServerInput.extend(idParam),
  }),
];
