import { z } from "zod";
import { CreateWorkflowInput, UpdateWorkflowInput } from "@open-agents/types";
import { defineControlPlaneTool, slugParam } from "../defineTool.js";

export const workflowControlPlaneTools = [
  defineControlPlaneTool({
    name: "workflows_list",
    title: "List workflows",
    description: "List workflows visible to the caller.",
    auth: "user",
    method: "GET",
    path: "/api/workflows",
    input: z.object({}),
  }),
  defineControlPlaneTool({
    name: "workflows_create",
    title: "Create workflow",
    description: "Create a new workflow draft.",
    auth: "operator",
    method: "POST",
    path: "/api/workflows",
    input: CreateWorkflowInput,
  }),
  defineControlPlaneTool({
    name: "workflows_get",
    title: "Get workflow",
    description: "Get full workflow configuration by slug.",
    auth: "user",
    method: "GET",
    path: "/api/workflows/:slug",
    pathParams: ["slug"],
    input: z.object(slugParam),
  }),
  defineControlPlaneTool({
    name: "workflows_update",
    title: "Update workflow",
    description: "Patch workflow draft fields (steps, access, surfaces).",
    auth: "operator",
    method: "PATCH",
    path: "/api/workflows/:slug",
    pathParams: ["slug"],
    input: UpdateWorkflowInput.extend(slugParam),
  }),
  defineControlPlaneTool({
    name: "workflows_publish",
    title: "Publish workflow",
    description: "Freeze the current draft into a new published workflow version.",
    auth: "operator",
    method: "POST",
    path: "/api/workflows/:slug/publish",
    pathParams: ["slug"],
    input: z.object(slugParam),
  }),
  defineControlPlaneTool({
    name: "workflows_delete",
    title: "Delete workflow",
    description: "Permanently delete a workflow.",
    auth: "operator",
    method: "DELETE",
    path: "/api/workflows/:slug",
    pathParams: ["slug"],
    input: z.object(slugParam),
  }),
  defineControlPlaneTool({
    name: "workflows_list_access",
    title: "List workflow access",
    description: "List users with explicit access when access mode is specific.",
    auth: "operator",
    method: "GET",
    path: "/api/workflows/:slug/access",
    pathParams: ["slug"],
    input: z.object(slugParam),
  }),
];
